# Classification: Fire And Not Fire

---

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
dataset = pd.read_csv('Raw-Algerian_forest_fires_dataset_UPDATE.csv', header = 1)
dataset.head(100)

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,01,06,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,02,06,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,03,06,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,04,06,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,05,06,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,04,09,2012,29,73,17,0.1,68.4,1.9,15.7,1.4,2.9,0.5,not fire
96,05,09,2012,29,75,16,0,80.8,3.4,24,2.8,5.1,1.7,fire
97,06,09,2012,29,74,19,0.1,75.8,3.6,32.2,2.1,5.6,0.9,not fire
98,07,09,2012,31,71,17,0.3,69.6,3.2,30.1,1.5,5.1,0.6,not fire
99,08,09,2012,30,73,17,0.9,62,2.6,8.4,1.1,3,0.4,not fire

# Dataset Cleaning

- Dataset is in two parts (Region)
- Merge them with a category 0 & 1 as per Region: (:122) as 0,  (122:) as 1 and Merge

In [3]:
dataset[dataset.isnull().any(axis=1)]

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
122,Sidi-Bel Abbes Region Dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,14,07,2012,37,37,18,0.2,88.9,12.9,14.6 9,12.5,10.4,fire,NaN

In [ ]:
# Merging Data Set
df = dataset
df.loc[:122, "Region"] = 0
df.loc[122:, "Region"] = 1 

df[["Region"]] = df[["Region"]].astype(int)

In [5]:
# Removing Nan and Redundant row
df.isnull().sum()
df = df.dropna().reset_index(drop=True)

df.iloc[122]
df = df.drop(122).reset_index(drop=True)

In [6]:
# Cleaing Column Name

df.columns = df.columns.str.strip()
df.columns

Index(['day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes', 'Region'],
      dtype='object')

In [7]:
# Converting DataType

df.info()
df['Temperature'].unique()

df[['day', 'month', 'year', 'Temperature', 'RH', 'Ws']] = df[['day', 'month', 'year', 'Temperature', 'RH', 'Ws']].astype(int)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          243 non-null    object
 1   month        243 non-null    object
 2   year         243 non-null    object
 3   Temperature  243 non-null    object
 4   RH           243 non-null    object
 5   Ws           243 non-null    object
 6   Rain         243 non-null    object
 7   FFMC         243 non-null    object
 8   DMC          243 non-null    object
 9   DC           243 non-null    object
 10  ISI          243 non-null    object
 11  BUI          243 non-null    object
 12  FWI          243 non-null    object
 13  Classes      243 non-null    object
 14  Region       243 non-null    int64
dtypes: int64(1), object(14)
memory usage: 28.6+ KB

In [8]:
objects = [features for features in df.columns if df[features].dtypes=='O']

for i in objects:
    if i != 'Classes':
        df[i] = df[i].astype(float)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          243 non-null    int64
 1   month        243 non-null    int64
 2   year         243 non-null    int64
 3   Temperature  243 non-null    int64
 4   RH           243 non-null    int64
 5   Ws           243 non-null    int64
 6   Rain         243 non-null    float64
 7   FFMC         243 non-null    float64
 8   DMC          243 non-null    float64
 9   DC           243 non-null    float64
 10  ISI          243 non-null    float64
 11  BUI          243 non-null    float64
 12  FWI          243 non-null    float64
 13  Classes      243 non-null    object
 14  Region       243 non-null    int64
dtypes: float64(7), int64(7), object(1)
memory usage: 28.6+ KB

In [9]:
df.to_csv('Cleaned-Algerian_forest_fires_dataset.csv', index=False)